version: '3'
services:
  web:
    build:
      context: .
      dockerfile: php-Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: mariadb-Dockerfile
    ports:
      - "3306:3306"